Controllers/AdminMakaleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_Blog_Website.Models;
using System.Web.Helpers;
using System.IO;

namespace MVC_Blog_Website.Controllers
{
    public class AdminMakaleController : Controller
    {

        mvcBlogDB db = new mvcBlogDB();
        // GET: AdminMakale
        public ActionResult Index()
        {
            var makales = db.Makales.ToList();
            return View(makales);       
        }

        // GET: AdminMakale/Details/5
        public ActionResult Details(int id)
        {
            var makale = db.Makales.Where(m => m.MakaleId == id).SingleOrDefault();
            return View(makale);
        }

        // GET: AdminMakale/Create
        public ActionResult Create()
        {
            ViewBag.kategoriId = new SelectList(db.Kategoris, "KategoriId", "KategoriAdi");
            return View();
        }

        // POST: AdminMakale/Create
        [HttpPost]
        public ActionResult Create(Makale makale, string etiketler, HttpPostedFileBase gorsel)
        {
            if (ModelState.IsValid)
            {
                if (gorsel != null)
                {
                    WebImage img = new WebImage(gorsel.InputStream);
                    FileInfo fotoinfo = new FileInfo(gorsel.FileName);
                    string newfoto = Guid.NewGuid().ToString() + fotoinfo.Extension;
                    img.Save("~/Uploads/MakaleFoto/" + newfoto);
                    makale.Gorsel = "/Uploads/MakaleFoto/" + newfoto;
                }
                else
                {
                    //Response.Write(@"< script language = 'javascript' > alert('Görsel alanı boş bırakılamaz.');</ script > ");
                    ViewBag.HataMesaji = "Görsel alanı boş bırakılamaz.";
                }
                if (etiketler != null)
                {
                    string[] etiketdizi = etiketler.Split(',');
                    foreach (var i in etiketdizi)
                    {
                        var yenietiket = new Etiket { EtiketAdi = i };
                        db.Etikets.Add(yenietiket);
                        var uyeid = Session["uyeid"];
                        makale.UyeId = Convert.ToInt32(uyeid);
                        makale.Okunma = 0;
                        makale.Tarih = DateTime.Now;
                        db.Makales.Add(makale);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    ViewBag.HataMesaji = "Görsel alanı boş bırakılamaz.";
                }
            }
            ViewBag.KategoriListesi = new SelectList(db.Kategoris, "KategoriId", "KategoriAdi");
            return View(makale);
        }

        // GET: AdminMakale/Edit/5
        public ActionResult Edit(int id)
        {
            var makale = db.Makales.Where(m => m.MakaleId == id).SingleOrDefault();
            if (makale == null)
            {
                return HttpNotFound();
            }
          
            ViewBag.kategoriId = new SelectList(db.Kategoris, "KategoriId", "KategoriAdi", makale.KategoriId);
            return View(makale);
        }

        // POST: AdminMakale/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, HttpPostedFileBase Gorsel, Makale makale)
        {
            try
            {
                var makales = db.Makales.Where(m => m.MakaleId == id).SingleOrDefault();
                if (Gorsel != null)
                {
                    if (System.IO.File.Exists(Server.MapPath(makales.Gorsel)))
                    {
                        System.IO.File.Delete(Server.MapPath(makales.Gorsel));
                    }
                    WebImage img = new WebImage(Gorsel.InputStream);
                    FileInfo fotoinfo = new FileInfo(Gorsel.FileName);
                    string newfoto = Guid.NewGuid().ToString() + fotoinfo.Extension;   
                    img.Save("~/Uploads/MakaleFoto/" + newfoto);
                    makales.Gorsel = "/Uploads/MakaleFoto/" + newfoto;
                }
                makales.Baslik = makale.Baslik;
                makales.Icerik = makale.Icerik;
                makales.KategoriId = makale.KategoriId;
                ViewBag.kategoriId = new SelectList(db.Kategoris, "KategoriId", "KategoriAdi", makale.KategoriId);
                db.SaveChanges();

                return RedirectToAction("Index");



            }

            catch
            {
                ViewBag.kategoriId = new SelectList(db.Kategoris, "KategoriId", "KategoriAdi", makale.KategoriId);
                return View(makale);
            }
        }

        // GET: AdminMakale/Delete/5
        public ActionResult Delete(int id)
        {
            var makale = db.Makales.Where(m => m.MakaleId == id).SingleOrDefault();
            if (makale == null)
            {
                return HttpNotFound();
            }
            return View(makale);
        }

        // POST: AdminMakale/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                var makales = db.Makales.Where(m => m.MakaleId == id).SingleOrDefault();
                if (makales == null)
                {
                    return HttpNotFound();
                }
                if (System.IO.File.Exists(Server.MapPath(makales.Gorsel)))
                {
                    System.IO.File.Delete(Server.MapPath(makales.Gorsel));
                }
                foreach (var i in makales.Yorums.ToList())
                {
                    db.Yorums.Remove(i);
                }
                foreach (var i in makales.Etikets.ToList())
                {
                    db.Etikets.Remove(i);
                }
                db.Makales.Remove(makales);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/AdminMakale/Create.cshtml
@model MVC_Blog_Website.Models.Makale

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="font-family:'Century Gothic';margin-left:15px;">Yeni Makale Oluştur</h2>

@using (Html.BeginForm("Create", "AdminMakale", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal" style="font-family:'Century Gothic';margin-left:15px;">
    <h4 style="font-family:'Century Gothic';margin-left:15px;">Makale</h4>
    <h1>@ViewBag.HataMesaji</h1>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group" style="font-family:'Century Gothic';">

        <div class="col-md-10">
            <label>Kategori Adı</label>
            @Html.DropDownList("KategoriId", null , htmlAttributes: new { @class = "form-control"  })
            @Html.ValidationMessageFor(model => model.KategoriId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            <label>Makale Başlık</label>
            @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control", @required = "" } })
            @Html.ValidationMessageFor(model => model.Baslik, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            <label>Makale İçerik</label>
            @Html.EditorFor(model => model.Icerik, new { htmlAttributes = new { @class = "form-control", @required = "" } })
            @Html.ValidationMessageFor(model => model.Icerik, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            <label>Makale Thumbnail</label>
            <input type="file" required name="gorsel" id="gorsel" accept=".jpg,.png,.jpeg,.gif" class="form-control" />
            @Html.ValidationMessageFor(model => model.Gorsel, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
        <div class="col-md-10">
            <label>Makale Tarih</label>
            @Html.EditorFor(model => model.Tarih, new { htmlAttributes = new { @class = "form-control", @type = "datetime-local", @required = "" } })
            @Html.ValidationMessageFor(model => model.Tarih, "", new { @class = "text-danger" })
        </div>
    </div>*@

    <div class="form-group">
        @Html.Label("Etiketler", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBox("Etiketler")
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-4">
            <a href="/AdminMakale/Index/"><input type="button" value="Geri Dön" class="btn btn-danger" /></a>
            <input type="submit" value="Oluştur" class="btn btn-info" />
        </div>
    </div>
</div>
}

Views/AdminMakale/Delete.cshtml
@model MVC_Blog_Website.Models.Makale

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="font-family:'Century Gothic';margin-left:15px;">Makaleyi Sil</h2>

<h4 style="font-family:'Century Gothic';margin-left:15px;">Makaleyi silmek istiyor musunuz ?</h4>
<div>
    <hr />
    <dl class="dl-horizontal" style="font-family:'Century Gothic';margin-left:15px;">
        <dt>
            <label>Kategori Adı</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kategori.KategoriAdi)
        </dd>

        <dt>
            <label>Başlık</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Baslik)
        </dd>

        <dt>
            <label>İçerik</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Icerik)
        </dd>

        <dt>
            <label>Thumbnail</label>
        </dt>

        <dd>
            <img src="@Model.Gorsel" width="150" />
            @*@Html.DisplayFor(model => model.Gorsel)*@
        </dd>

        <dt>
            <label>Tarih</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tarih)
        </dd>

        <dt>
            <label>Üye Id</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UyeId)
        </dd>

        <dt>
            <label>Okunma</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Okunma)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-group">
            <div class="col-md-offset-2 col-md-4">
                <a href="/AdminMakale/Index/"><input type="button" value="Geri Dön" class="btn btn-danger" /></a>
                <input type="submit" value="Sil" class="btn btn-info" />
            </div>
        </div>
    }
</div>

Views/AdminMakale/Details.cshtml
@model MVC_Blog_Website.Models.Makale

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="font-family:'Century Gothic';margin-left:15px;">Makale Detay</h2>

<div>
    <h4 style="font-family:'Century Gothic';margin-left:15px;">Makale</h4>
    <hr />
    <dl class="dl-horizontal" style="font-family:'Century Gothic';margin-left:15px;">
        <dt>
            <label>Makale Adı</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kategori.KategoriAdi)
        </dd>

        <dt>
            <label>Makale Başlık</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Baslik)
        </dd>

        <dt>
            <label>Makale İçerik</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Icerik)
        </dd>

        <dt>
            <label>Makale Thumbnail</label>
        </dt>

        <dd>
            <img src="@Model.Gorsel" width="150" />
        </dd>

        <dt>
            <label>Makale Tarih</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tarih)
        </dd>

        <dt>
            <label>Üye Id</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UyeId)
        </dd>

        <dt>
            <label>Okunma</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Okunma)
        </dd>

    </dl>
</div>
<p>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-4">
            <a href="/AdminMakale/Index/"><input type="button" value="Geri Dön" class="btn btn-danger" /></a>
            @Html.ActionLink("Düzenle", "Edit", new { id = Model.MakaleId }, htmlAttributes: new { @class = "btn btn-info" })
        </div>
    </div>
</p>

Views/AdminMakale/Edit.cshtml
@model MVC_Blog_Website.Models.Makale

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="font-family:'Century Gothic';margin-left:15px;">Makaleyi Düzenle</h2>

@using (Html.BeginForm("Edit", "AdminMakale", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="font-family:'Century Gothic';margin-left:15px;">
        <h4 style="font-family:'Century Gothic';margin-left:15px;">Makale</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MakaleId)

        <div class="form-group">

            <div class="col-md-10">
                <label>Kategori</label>
                @Html.DropDownList("KategoriId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.KategoriId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">

            <div class="col-md-10">
                <label>Makale Başlık</label>
                @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Baslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <label>Makale İçerik</label>
                @Html.EditorFor(model => model.Icerik, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.Icerik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-10">Makale Eski Thumbnail</label>
            <div class="col-md-10">

                <img width="150" src="@Model.Gorsel" />
                @Html.ValidationMessageFor(model => model.Gorsel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <label>Makale Yeni Thumnbnail</label>
                <input type="file" name="gorsel" id="gorsel" accept=".jpg,.png,.jpeg,.gif" class="form-control" />
                @Html.ValidationMessageFor(model => model.Gorsel, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            <div class="col-md-10">
                <label>Makale Tarih</label>
                @Html.EditorFor(model => model.Tarih, new { htmlAttributes = new { @class = "form-control", @type = "datetime-local" } })
                @Html.ValidationMessageFor(model => model.Tarih, "", new { @class = "text-danger" })
            </div>
        </div>*@





        <div class="form-group">
            <div class="col-md-offset-2 col-md-4">
                <a href="/AdminMakale/Index/"><input type="button" value="Geri Dön" class="btn btn-danger" /></a>
                <input type="submit" value="Kaydet" class="btn btn-info" />
            </div>
        </div>
    </div>
}

Views/AdminMakale/Index.cshtml
@model IEnumerable<MVC_Blog_Website.Models.Makale>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="font-family:'Century Gothic';margin-left:15px;">Makaleler</h2>

<p style="font-family:'Century Gothic';margin-left:15px;">
    @Html.ActionLink("Yeni Makale Oluştur", "Create")
</p>
<table class="table table-responsive-md" style="font-family:'Century Gothic';">
    <tr>
        <th>
            <label>Makale Adı</label>
        </th>
        <th>
            <label>Makale Başlık</label>
        </th>
        <th>
            <label>Makale İçerik</label>
        </th>
        <th>
            <label>Makale Thumbnail</label>
        </th>
        <th>
            <label>Makale Tarih</label>
        </th>
        <th>
            <label>Üye Id</label>
        </th>
        <th>
            <label>Okunma</label>
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Kategori.KategoriAdi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Baslik)
            </td>
            <td>
                @if (item.Icerik.Length>100)
                {
                   <p style="font-family:'Century Gothic';"> @Html.Raw(item.Icerik.Substring(0, 200))<font size="4" color="red" >...(Devam)</font></p>
                }
                else
                {
                   <p style="font-family:'Century Gothic';"> @Html.Raw(item.Icerik)</p>
                }
                @*@Html.DisplayFor(modelItem => item.Icerik)*@
            </td>
            <td>
                <img width="75" src="@item.Gorsel" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tarih)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UyeId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Okunma)
            </td>
            <td>
                @Html.ActionLink("Düzenle", "Edit", new { id = item.MakaleId }) |
                @Html.ActionLink("Detay", "Details", new { id = item.MakaleId }) |
                @Html.ActionLink("Sil", "Delete", new { id = item.MakaleId })
            </td>
        </tr>
    }

</table>