Controllers/AdminKategoriController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC_Blog_Website.Models;

namespace MVC_Blog_Website.Controllers
{
    public class AdminKategoriController : Controller
    {
        private mvcBlogDB db = new mvcBlogDB();

        // GET: AdminKategori
        public ActionResult Index()
        {
            return View(db.Kategoris.ToList());
        }

        // GET: AdminKategori/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kategori kategori = db.Kategoris.Find(id);
            if (kategori == null)
            {
                return HttpNotFound();
            }
            return View(kategori);
        }

        // GET: AdminKategori/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminKategori/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "KategoriId,KategoriAdi")] Kategori kategori)
        {
            if (ModelState.IsValid)
            {
                db.Kategoris.Add(kategori);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(kategori);
        }

        // GET: AdminKategori/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kategori kategori = db.Kategoris.Find(id);
            if (kategori == null)
            {
                return HttpNotFound();
            }
            return View(kategori);
        }

        // POST: AdminKategori/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "KategoriId,KategoriAdi")] Kategori kategori)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kategori).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(kategori);
        }

        // GET: AdminKategori/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kategori kategori = db.Kategoris.Find(id);
            if (kategori == null)
            {
                return HttpNotFound();
            }
            return View(kategori);
        }

        // POST: AdminKategori/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Kategori kategori = db.Kategoris.Find(id);
            db.Kategoris.Remove(kategori);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/AdminKategori/Create.cshtml
@model MVC_Blog_Website.Models.Kategori

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="margin-left:10px;font-family:'Century Gothic';">Kategori Oluştur</h2>

@using (Html.BeginForm("Create", "AdminKategori", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="margin-left:10px;font-family:'Century Gothic';">
        <h4 style="margin-left:10px;font-family:'Century Gothic';">Kategori</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Kategori Adı</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.KategoriAdi, new { htmlAttributes = new { @class = "form-control", @required = "" } })
                @Html.ValidationMessageFor(model => model.KategoriAdi, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-4">
            <a href="/AdminKategori/Index/"><input type="button" value="Geri Dön" class="btn btn-danger" /></a>
            <input type="submit" value="Oluştur" class="btn btn-info" />
        </div>
    </div>

}

Views/AdminKategori/Delete.cshtml
@model MVC_Blog_Website.Models.Kategori

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="font-family:'Century Gothic';margin-left:15px;">Kategoriyi Sil</h2>

<h3 style="font-family:'Century Gothic';margin-left:15px;">Kategoriyi silmek istiyor musunuz ?</h3>
<div>
    <hr />
    <dl class="dl-horizontal" style="font-family:'Century Gothic';margin-left:15px;">
        <dt>
            <label class="control-label ">Kategori Adı</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KategoriAdi)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-group">
            <div class="col-md-offset-2 col-md-4">
                <a href="/AdminKategori/Index/"><input type="button" value="Geri Dön" class="btn btn-danger" /></a>
                <input type="submit" value="Sil" class="btn btn-info" />
            </div>
        </div>
    }
</div>

Views/AdminKategori/Details.cshtml
@model MVC_Blog_Website.Models.Kategori

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="font-family:'Century Gothic';margin-left:15px;">Kategori Detay</h2>

<div>
    <h4 style="font-family:'Century Gothic';margin-left:15px;">Kategori</h4>
    <hr />
    <dl class="dl-horizontal" style="font-family:'Century Gothic';margin-left:15px;">
        <dt>
            <label>Kategori Adı</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KategoriAdi)
        </dd>

    </dl>
</div>
<p>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-4">
            <a href="/AdminKategori/Index/"><input type="button" value="Geri Dön" class="btn btn-danger" /></a>
            @Html.ActionLink("Düzenle", "Edit", new { id = Model.KategoriId }, htmlAttributes: new { @class = "btn btn-info" })
        </div>
    </div>
</p>

Views/AdminKategori/Edit.cshtml
@model MVC_Blog_Website.Models.Kategori

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="font-family:'Century Gothic';margin-left:15px;">Kategoriyi Düzenle</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="font-family:'Century Gothic';margin-left:15px;">
        <h4 style="font-family:'Century Gothic';margin-left:15px;">Kategori</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.KategoriId)

        <div class="form-group">
            <div class="col-md-10">
                <label>Kategori Adı</label>
                @Html.EditorFor(model => model.KategoriAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KategoriAdi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-4">
                <a href="/AdminKategori/Index/"><input type="button" value="Geri Dön" class="btn btn-danger" /></a>
                <input type="submit" value="Kaydet" class="btn btn-info" />
            </div>
        </div>
    </div>
}

Views/AdminKategori/Index.cshtml
@model IEnumerable<MVC_Blog_Website.Models.Kategori>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="font-family:'Century Gothic';margin-left:15px;">Kategoriler</h2>

<p style="font-family:'Century Gothic';margin-left:15px;">
    @Html.ActionLink("Yeni Kategori Oluştur", "Create")
</p>
<table class="table" style="font-family:'Century Gothic';margin-left:15px;">
    <tr>
        <th>
            <label>Kategori Adı</label>
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.KategoriAdi)
            </td>
            <td>
                @Html.ActionLink("Düzenle", "Edit", new { id = item.KategoriId }) |
                @Html.ActionLink("Detay", "Details", new { id = item.KategoriId }) |
                @Html.ActionLink("Sil", "Delete", new { id = item.KategoriId })
            </td>
        </tr>
    }

</table>